version: "2"

services:

# ============= MongoDB
  mongodb:
    container_name: mongodb__ctnr
    image: demo-mongodb
    ports:
      - 27017:27017

# ============= MONGODB-UI :
  mongodb-ui:
    container_name: mongodb-ui__cntr
    image: demo-mongodb-ui
    environment:
      - HOST=0.0.0.0
    ports:
      - 1234:1234

# ============= NODE-API :
  node-api:
    container_name: node-api__ctnr
    image: demo-node-api
    ports:
      - 4040:4040

