#=======================
# pour builder l'image (ce placer dans le repertoire du dockerfle):
# docker build -t demo-mongodb .

# lance le container
# docker run --rm --name demo-mongodb__ctnr demo-mongodb

FROM mongo:3.4

MAINTAINER laurent.v

CMD ["mongod"]